### ISSUE TITLE
getFrenchTitle bug

### ISSUE THREAD

**Issue by nsvir** [djoole/couchpotato.provider.t411#26]
I could not get t411 working with couchpotato
Here is my error:

File "/var/lib/couchpotato/custom_plugins/t411/main.py", line 200, in getFrenchTitle
    if data['results'] != None:
TypeError: list indices must be integers, not str

**Comment by djoole** [comment]
#25 duplicate

CP put down TMDB connections because TMDB was unavailable for 15 times in a row.

I might change the plugin so that i continues searching only VO titles if getFrenchTitle fails.
But it's not a great solution.

**Comment by gogui51** [comment]
Hey,
I don't understand how do you fix (or your get around) the problem...

Even if I search an english title CP doesn't propose me the t411 torrent...

An idea how to fix it ?
Thanks a lot

exemple of error :

`[ t411] Failed to parse TMDB API: Traceback (most recent call last): File "/home/couchpotato/.couchpotato/custom_plugins/t411/main.py", line 200, in getFrenchTitle if data['results'] != None: TypeError: list indices must be integers, not str``

**Comment by djoole** [comment]
There is no fix.

The work around is wait for TMDB to be available again.
Unfortunately, couchpotato blacklist TMDB for 15 minutes, if TMDB doesn't answer.

You could try to post an issue/request on ruudburger CP to ask for a customisable setting allowing user to set the blacklist timer (15 min by default).

But as it is right now, you just have to be patient and the plugin will eventually be able to use TMDB to get the french title.

I'm not feeling brave enough to modify my code in order to avoid TMDB use in the case it's blacklisted.. Feel free to post a PR if you're motivated.
